### ISSUE TITLE
cannot post test using Postman.

### ISSUE THREAD

**Issue by sassy** [line/clova-extension-sample-dice#3]
sorry, Japanese.

https://github.com/line/clova-extension-sample-dice#usage
についてですが、
Postmanの検証ができません。
多分、POSTにSignatureCEKヘッダーの値がなくてはならないので、
signatureのverifierで失敗し、400になってしまいます。

responseも
Missing signature. が返ってきます。

**Comment by qtamaki** [comment]
私も同じ状況です。

**Comment by qtamaki** [comment]
プルリク #4 しました

**Comment by dzeyelid** [comment]
途中から失礼します。おそらく、こちらのシグネチャ生成を行い、ヘッダとして付与する想定かと思います。
https://clova-developers.line.me/guide/#/CEK/Guides/Build_Custom_Extension.md#RequestMessageValidation

**Comment by qtamaki** [comment]
本番に繋げば普通に動きます。サンプルを説明通りに実行すると原因不明のエラーで動かないので、初見殺しすぎますね。テストも困難になりますし。

**Comment by tada3** [comment]
@sassy  さん、ご指摘ありがとうございます。確かにPostman等でテストする時にSignature検証でエラーになるのは不便だと思います。
対応として、Signature検証をなくしてしまうとサンプルとして正しい動きではなくなってしまうので #5 の方を採用させて頂きます。
